### PR TITLE
adding Wave Terminal to the list

### PR DESCRIPTION
**Pull request by gonzolively**
I'd like to add our product, Wave Terminal to your wonderful list!

Thanks 🙏

### CODE REVIEW

**Review by cdleon — CHANGES_REQUESTED** [review]
Needs to be added also to Linux list correct?

**Comment by gonzolively** [comment]
Yes, great catch @cdleon !

Thanks 🙏

**Comment by gonzolively** [comment]
@cdleon , is there anything else that needs to be done?

**Review by cdleon — APPROVED** [review]

**Comment by cdleon** [comment]
> @cdleon , is there anything else that needs to be done?

no thnx! didn't have notifications on and missed all PR changes

**Pull request merged**
